name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Укажите версию Python, которую вы используете

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage coveralls  # Установите зависимости для тестирования и покрытия

      - name: Run tests with coverage
        run: |
          coverage run -m pytest test_quadratic_roots.py  # Запуск тестов с покрытием

      - name: Generate coverage report
        run: |
          coverage xml  # Генерация отчета покрытия в формате XML

      - name: Submit coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}  # Используйте ваш токен из Secrets
        run: |
          coveralls

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
        with:
          args: >
            -Dsonar.projectKey=Alexanderkona_pythontest
            -Dsonar.organization=sani
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml
